-- AlterTable
ALTER TABLE "system_settings" ADD COLUMN     "alipayAppId" TEXT,
ADD COLUMN     "alipayEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "alipayPrivateKey" TEXT,
ADD COLUMN     "emailFrom" TEXT,
ADD COLUMN     "emailFromName" TEXT,
ADD COLUMN     "emailNotifications" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "inventoryAlerts" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "orderNotifications" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "smsNotifications" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "smtpHost" TEXT,
ADD COLUMN     "smtpPassword" TEXT,
ADD COLUMN     "smtpPort" INTEGER DEFAULT 587,
ADD COLUMN     "smtpSecure" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "smtpUser" TEXT,
ADD COLUMN     "stripeEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "stripePublicKey" TEXT,
ADD COLUMN     "stripeSecretKey" TEXT,
ADD COLUMN     "userNotifications" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "wechatPayApiKey" TEXT,
ADD COLUMN     "wechatPayEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "wechatPayMchId" TEXT;
